### ISSUE TITLE
Config incompatibilities with Sodium + Indium

### ISSUE THREAD

**Issue by hugeblank** [Juuxel/Adorn#166]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.13.0
- Minecraft: 1.16.5
- Fabric Loader: 0.11.3
- Fabric API: 0.34.2

### Describe the bug
When changing the "sittingOnTables" option to `true` on the client, and joining the server, the user gets around 10 seconds to witness chaos followed by an immediate crash. I have all users install "Not Enough Crashes" and it blames Sodium, sharing it here as well, since this could be an issue with the vanilla renderer too. Additionally since I am using Indium I have directed all issues where Sodium takes the blame to their github. The general crash to do with `nextNode` is very common among my server members, and I have reported it here: comp500/Indium#55. However, this particular crash was distinctly due to changing that config value.

Crash Report: [crash.txt](https://gist.githubusercontent.com/natanfudge/2f9c065338046586f81c1fb56c7f1fb4/raw/e42998cbbd86c594f31eb151b52a2894ce42cb08/crash.txt)

Chaos: 
![image](https://user-images.githubusercontent.com/16393543/119953488-e713f380-bf52-11eb-8b62-b562f79b6a83.png)

### Expected behavior

Not Chaos: 
![image](https://user-images.githubusercontent.com/16393543/119953816-3fe38c00-bf53-11eb-9094-402fa646a383.png)

Also, not a crash

**Comment by Juuxel** [comment]
The "chaos" you're seeing is a registry sync bug. The config option `sittingOnTables` has to be the same on the server and all clients/users since it affects the block states of the table. (This config option has proved very error-prone, so it will be removed in MC 1.17)

The crash itself has nothing to do with Adorn, but some sort of CME with Sodium/Indium. It's not caused by Adorn's config, at least directly, but I wouldn't be surprised if the same desync bug caused that as well.

**Comment by hugeblank** [comment]
Thanks for the quick response! That makes a lot of sense. I'll warn my friends to not mess with that config value. As for the CME being caused by the registry sync bug, that could be very helpful for my issue with Indium, thanks again for the heads up about it.

**Comment by Juuxel** [comment]
`sittingOnTables` has been removed in Adorn 2.0, so this shouldn't happen anymore.
