### ISSUE TITLE
Brewer and kitchen sink improvements

### ISSUE THREAD

**Issue by DWX12** [Juuxel/Adorn#250]
Using 1.18 forge currently.

Would like to see NEI support for the brewer. In addition, for drinks aside from hot chocolate, should use some sort of water on one side instead of just one specific ingredient (water bottle, water bucket, etc.).

Some details that could be added to the brewer would be some particles when it is active and possibly some gurgling sound effects.

For the kitchen sink, would like to see a config option to allow it to be used as an infinite water source block or act sort of like a cauldron with the ability to say shift+click on it to empty it.

Thank you for taking the time to make this mod and look forward to seeing further changes and improvements to it.

**Comment by Juuxel** [comment]
> Would like to see NEI support for the brewer.

NEI doesn't exist for any MC version where you can have Adorn. If you mean JEI, I might add support for it at some point. REI also works already and should be compatible with mods that use JEI. (I chose to add REI support first since it works both on Fabric and Forge)

> In addition, for drinks aside from hot chocolate, should use some sort of water on one side instead of just one specific ingredient (water bottle, water bucket, etc.).

I might add this for *some* of them where the liquid doesn't come from the ingredient itself (like with berries).

> For the kitchen sink, would like to see a config option to allow it to be used as an infinite water source block

This is already implemented for the next release, though I have no ETA for when I'll publish it.

Thanks for all the feedback, I appreciate it :^)
