### ISSUE TITLE
Request for more documentation.

### ISSUE THREAD

**Issue by legoatoom** [Juuxel/Adorn#256]
Adorn is a project that it setup differently than most mods as it:
- Uses Architectury to build Forge and Fabric simultaneously. 
- Works with Kotlin instead of Java.

To have both is quite amazing. 
My experience with gradle is minimal and if I would want to create a mod with Architectury and Kotlin it is quite difficult to know what needs to be done to set this up / migrate an existing project.
Thus this issue is a request for documentation in the all the `build.gradle.kt` files and what each section in gradle does and why certain dependencies were used.

Possible details about how/why `datagen` is setup would also be appreciated.  
Many people use other mods as references and examples to create their own mods, more documentation would greatly help this.

**Comment by Juuxel** [comment]
I added a lot of docs in bd70a2955640897bc68ff1f4f201fe5e6c10bc32 :^)

There's nothing special needed for using Kotlin instead of Java, really, other than applying the corresponding Gradle plugin (`org.jetbrains.kotlin.jvm`) and using the Fabric Language Kotlin/Kotlin for Forge language adapters according to their instructions.

Migrating an existing project is a bit more work, but can generally be done if you move the Fabric/Forge code into that specific subproject and create the new root/`common` projects as needed. It might also be easier to use an [Architectury template](https://github.com/architectury/architectury-templates) and copy the code there.
