### ISSUE TITLE
Brewer (forge)

### ISSUE THREAD

**Issue by imnotklaus** [Juuxel/Adorn#262]
I'm not sure where to put this, so I figured I'd put it here, I can't see any documentation on the "Brewer" (forge), so I'm asking here- how do I put the "air" in it? Like how do I power it? Very confused and nobody I've asked knows.

**Comment by Juuxel** [comment]
![diagram of input slots](https://user-images.githubusercontent.com/6596629/168893056-a301806a-864f-4833-8c09-939c825f89f5.png)

Basically:

- You put your "solid ingredients" as shown in REI into slots `1` and `2`.
- Into slot `3` goes your mug, which will be filled with the drink.
- The tank `4` (which can be filled through slot `5`) can be used instead of a water or milk bucket to provide fluids to the recipe if you want to. You can also put the fluids as buckets into slot `1` or `2`.

You definitely do not put any air in it. (And it needs no power, consider that the magic of furniture mods!)

**Comment by imnotklaus** [comment]
OOH! Thank you so much!
