### ISSUE TITLE
JEI support for brewer recipes

### ISSUE THREAD

**Issue by jlaine3333** [Juuxel/Adorn#269]
### Versions of Minecraft, Forge and Adorn
- Adorn: 3.5.0
- Minecraft: 1.18.2
- Forge: 40.1.60

### Describe the bug
Brewer recipes aren't registered in JEI. Happens with no other mods installed and a clean config for both mods.

### To Reproduce
1. Install Adorn and JEI
2. Attempt to open recipes for any brewer-related drink or for the brewer itself
3. No recipes will be available

### Expected behavior
JEI shows recipes for any brewer drinks

**Comment by Juuxel** [comment]
Not really a bug per se - Adorn just doesn't have support for showing brewer recipes in JEI. I'll probably add it though since it should be pretty simple.

For now, you can view the recipes using REI (Roughly Enough Items) or use this list:

- mug + glow berries = glow berry tea
- mug + cocoa beans + milk bucket (or a modded milk) = hot chocolate
- mug + cocoa beans + 250 L milk = hot chocolate
- mug + nether wart + 250 L water = nether wart coffee
- mug + nether wart + water bucket = nether wart coffee
- mug + sweet berries = sweet berry juice
