### ISSUE TITLE
Anyone can break someone else's trading station and keep all the items inside it

### ISSUE THREAD

**Issue by PedalHat29861** [Juuxel/Adorn#272]
There should be an option so that only the owner can break his own trading station

**Comment by Juuxel** [comment]
This was the case in old Adorn, but it was really buggy and led to unbreakable trading stations. Other can't keep "all the items" anyway if you have the locked trading station game rule enabled since only the owner can open it.

You can use a world protection mod to prevent breaking blocks if necessary, but that's not a decoration mod's job.

**Comment by superon** [comment]
You can use a world protection mod to prevent breaking blocks if necessary, but that's not a decoration mod's job...
just use a chest, has the same use and has the added bonus of being able to accept payment with things you don't already own :)
