### ISSUE TITLE
Missing Language For Kotlin In Latest Update

### ISSUE THREAD

**Issue by Sonifluous** [Juuxel/Adorn#311]
I have come across the following error when launching my game with the latest Adorn update:

[main/ERROR] [net.minecraftforge.fml.loading.LanguageLoadingProvider/LOADING]: Missing language kotlinforforge version [4.1,) wanted by Adorn-4.2.0+1.19.4-forge.jar, found 3.12.0

I believe there was a mix-up during the update launch, and wanted to notify of the error since I see no other tickets stating this issue

**Comment by RechercheRaptor** [comment]
Yeah there's some kind of version mixup, I have a 1.19.2 profile but CurseForge let me install/update to a 1.19.4 version of Adorn that then demanded the 4.1 kotlin, which wasn't displayed as an option for 1.19.2. I wound up going back down to the version of Adorn released on March 26th because for some reason with the version released on May 5th my launcher screen would black out

**Comment by Juuxel** [comment]
I accidentally published 4.2.0 as a 1.19.2 version at first, but fixed it pretty quickly (#310). I'm not sure if CurseForge has cached the wrong data locally for you. You can always get the latest 1.19.2 release here on Github: https://github.com/Juuxel/Adorn/releases/tag/3.8.3
