### ISSUE TITLE
Copper Pipes Do Not Connect to Other Blocks

### ISSUE THREAD

**Issue by tetraever** [Juuxel/Adorn#345]
### Adorn version

Adorn-5.3.0+1.20.4-fabric

### Minecraft version

1.20.4

### Mod loader

Fabric

### Mod loader version

fabric-loader-0.14.24-1.20.1   -   fabric-api-0.96.11+1.20.4

### Describe the bug

Copper pipes connect to other copper pipes but not to other blocks, meaning they are always floating.

### To reproduce

Place down copper pipes.

**Comment by Juuxel** [comment]
This is currently intentional behaviour and it's controlled by the `#adorn:copper_pipes_connect_to` tag (which only contains all the different copper pipes):
https://github.com/Juuxel/Adorn/blob/db15e7de9f578bfb027a0544efb053b709bed86f/common/src/main/resources/data/adorn/tags/blocks/copper_pipes_connect_to.json#L1-L6

I could make them connect to some other blocks in the future, though. Feel free to give me suggestions :)
