### ISSUE TITLE
Stone torches are completely waterproof

### ISSUE THREAD

**Issue by AwwShoot** [Juuxel/Adorn#80]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.8.4
- Minecraft: 1.15.2
- Fabric Loader: 
- Fabric API: 

### Describe the bug
Flowing water does not destroy stone torches. Torches can be waterlogged and still produce light.

### To Reproduce
1. Go to 'water'
2. Click on 'water with a stone torch'
3. Scroll down to 'look at the water'

### Expected behavior
flowing water would destroy the torch like a normal torch, and that stone torches should not function/exist waterlogged.

**Comment by dandin87** [comment]
> ### Describe the bug
> Flowing water does not destroy stone torches. Torches can be waterlogged and still produce light.
> ### Expected behavior
> flowing water would destroy the torch like a normal torch, and that stone torches should not function/exist waterlogged.

Actually I think the bug is that sometimes the torch stays lit and is not waterlogged when placed underwater. Since it has an unlit texture while waterlogged I would think the intention is that it does not float away in water.

I have extensively used this bug to place lit stone torches underwater. However, when they are actually waterlogged (pour a bucket of water on the placed torch) they do go out, and remain placed which seems to be intended.
